### ISSUE TITLE
MultiplicativeGaussianNoiseModel.cpp: default bias should be 1.0

### ISSUE THREAD

**Issue by JanGunheD** [peci1/gazebo_noisy_depth_camera#1]
In MultiplicativeGaussianNoiseModel.cpp:

_buffer[i] *= static_cast<float>(
          ignition::math::Rand::DblNormal(this->mean, this->stdDev) + this->bias);

works better when changed like this:

_buffer[i] *= static_cast<float>(
          ignition::math::Rand::DblNormal(this->mean, this->stdDev) + 1.0);

Otherwise the result will randomly change around 0 and not around the input value. The _buffer[i] should be multiplied by a random variation of 1, not of 0.

The most elegant way of changing this would be to set the bias to 1, but I did not find a way to do that in the URDF noise-tag of the depth-sensor.

**Comment by peci1** [comment]
It's just about how you understand the meaning of the parameters. Given that this is a multiplicative model and you set its parameters `mean` and `stdDev`, it comes natural to me that the default `mean` should be 1. If you set it like that, then there's no need to change the bias.

Maybe I should update the docs to say that more clearly.

**Comment by peci1** [comment]
I added a comment in e5623c0. Do you think that's enough for an explanation?

**Comment by JanGunheD** [comment]
Yes, that solved it for me, thanks for the quick help!
