### ISSUE TITLE
Unable to load custom sensor into Gazebo

### ISSUE THREAD

**Issue by Stan850** [peci1/gazebo_noisy_depth_camera#2]
Hi, recently I have been trying to load the noisy depth sensor from this repo into gazebo but was unsuccessful in doing so. I cloned this repo and the gazebo_custom_sensor_preloader repo into their own ROS packages and built them separately under a single workspace. After creating a launch file to run gazebo with the preloader plugin and a world containing a depth camera, I didn't see any msgs being printed into the terminal to indicate that the sensor was loaded. 

Instead, I decided to try and get the existing example_custom_sensor loaded into gazebo (using the preloader plugin) however that did not work out (same issue as above). I only changed the type from its original type "example_custom_sensor" to "depth" so that I would expect to see msgs being printed out in a terminal when I insert a random depth camera into a gazebo world.

Essentially I was hoping that someone could answer the following two questions:
1) Whether the procedure I used to load the noisy depth camera sensor into gazebo was correct in the first place?
2) Why I'm unable to load a custom sensor in general using the preloader plugin? I think this has something to do with classloader not being able to extract class information for the sensor as loader.getDeclaredClasses() returns nothing for me

Thanks in advance.

**Comment by Stan850** [comment]
Update: I did get the plugin to work as I see the right msgs being printed out into the terminal. It seems to have an effect on the image view I see from the topic visualizer however I'm not sure why the noise doesn't seem to be distributed across the whole image:

![Screenshot from 2021-07-07 17-17-18](https://user-images.githubusercontent.com/39651678/124830206-8b705900-df47-11eb-8a29-c9127bdb88ce.png)

**Comment by peci1** [comment]
I guess this is just a visualization issue. The 16bit depth image is transformed to be displayed as 8bit grayscale bitmap, so you lose information. Another issue could be that you're adding additive noise and not multiplicative - the further parts would then receive relatively lower amount of noise than the closer points. That's why I implemented the multiplicative noise which adds more noise to the further points than to the closer ones.

**Comment by Stan850** [comment]
Thanks for the info above. Seems like by putting objects and the camera in an enclosed space the depth images make much more sense. Guess I can confirm that this plugin is capable of working with ROS2 and gazebo11. Will close this until I find another issue.

![Screenshot from 2021-07-12 10-17-30](https://user-images.githubusercontent.com/39651678/125303512-dcdb6800-e2fa-11eb-989f-54356060c8be.png)

**Comment by peci1** [comment]
Great to hear it works in the end!
