### ISSUE TITLE
Noise has no effect due to wrong depth frame hook order

### ISSUE THREAD

**Issue by Martin-Oehler** [peci1/gazebo_noisy_depth_camera#3]
Hi,
first of all thank you for this awesome plugin. It is beyond me why Gazebo does not offer any sensible noise model for depth images at all, given their wide-spread use in robotics.

At first, I could not see any change when loading this plugin and I figured out why. In this comment it says https://github.com/peci1/gazebo_noisy_depth_camera/blob/f0205b41d735073c07647d8ea0cc291224104553/src/NoisyDepthCameraSensor.cpp#L78

However, this assumption seems to be wrong (at least in my setup with ROS Noetic, Gazebo 11.11.0).

The `NoisyDepthCameraSensor::init()` method calls the `DepthCameraSensor::Init();` before registering the callback to apply the noise model:https://github.com/peci1/gazebo_noisy_depth_camera/blob/f0205b41d735073c07647d8ea0cc291224104553/src/NoisyDepthCameraSensor.cpp#L56

But that function also calls `Sensor::Init()` [here](https://github.com/gazebosim/gazebo-classic/blob/e4b4d0fb752c7e43e34ab97d0e01a2a3eaca1ed4/gazebo/sensors/DepthCameraSensor.cc#L133) which in turns loads all the plugins first [here](https://github.com/gazebosim/gazebo-classic/blob/e4b4d0fb752c7e43e34ab97d0e01a2a3eaca1ed4/gazebo/sensors/Sensor.cc#L161).

Therefore, the plugins which publish the depth images are **always** loaded before registering the noise callback and the noise has no effect.

The only way I came up with to fix this is to basically copy the complete functionality of `DepthCameraSensor` and register the noise hook before `Sensor::Init()` (not committed yet, it is somewhat of a mess right now).

Best regards,
Martin

**Comment by peci1** [comment]
Hi, I'm not at the computer this week. Just a quick idea: do you use this plugin with https://github.com/peci1/gazebo_custom_sensor_preloader ? It won't work without it.

Or at least I think so. It's been some time since I worked on this.

**Comment by Martin-Oehler** [comment]
Yes, I guess otherwise the custom sensor plugin would not have been loaded at all. I verified that the hook order is the problem by printing the event id of the callback and also by adding prints to the noise callback as well as the depth camera plugin callback.

My changes regarding the ordering of the `Sensor::Init()` call also fixed the problem. I am just a bit confused how it could have worked previously. Maybe something in the Gazebo implementation changed.

**Comment by peci1** [comment]
This is really weird. I've tested it locally and it works for me as is.

Test file:

<details>

<summary>depth_camera.sdf</summary>

```
<?xml version="1.0" ?>
<sdf version="1.5">
  <world name="default">
    <include>
      <uri>model://ground_plane</uri>
    </include>
    <include>
      <uri>model://sun</uri>
    </include>
    <model name="sphere">
      <pose>2 0 0 0 0 0</pose>
      <link name="body">
        <inertial>
          <inertia>
            <ixx>1</ixx>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyy>1</iyy>
            <iyz>0</iyz>
            <izz>1</izz>
          </inertia>
          <mass>1.0</mass>
        </inertial>
        <collision name="geom">
          <geometry>
            <sphere>
              <radius>1</radius>
            </sphere>
          </geometry>
        </collision>
        <visual name="visual">
          <geometry>
            <sphere>
              <radius>1</radius>
            </sphere>
          </geometry>
          <material>
            <script>Gazebo/WoodPallet</script>
          </material>
        </visual>
      </link>
      <static>true</static>
    </model>
    <model name="camera_model">
      <pose>0 0 0 0 0 0</pose>
      <link name="my_link">
        <inertial>
          <inertia>
            <ixx>1</ixx>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyy>1</iyy>
            <iyz>0</iyz>
            <izz>1</izz>
          </inertia>
          <mass>1.0</mass>
        </inertial>
        <collision name="collision">
          <geometry>
            <box>
              <size>1 1 1</size>
            </box>
          </geometry>
        </collision>
        <sensor name="camera" type="depth">
          <camera>
            <horizontal_fov>1.04719755</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
            </image>
            <clip>
              <near>0.1</near>
              <far>20</far>
            </clip>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.2</stddev>
            </noise>
          </camera>
          <always_on>true</always_on>
          <update_rate>10</update_rate>
        </sensor>
      </link>
      <static>true</static>
    </model>
  </world>
</sdf>
```

</details>

```
$ gzserver -s libgazebo_custom_sensor_preloader.so depth_camera.world --verbose

Gazebo multi-robot simulator, version 11.14.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 172.17.0.1
[Msg] CustomSensorPreloader: Preloaded custom sensor RotatingLidarSensor from library /media/data/subt/thirdparty/ws/devel_n/lib/libgazebo_rotating_lidar.so
[Msg] CustomSensorPreloader: Preloaded custom sensor ExampleCustomSensor from library /media/data/subt/thirdparty/ws/devel_n/lib/libexample_custom_sensor.so
[Msg] CustomSensorPreloader: Preloaded custom sensor NoisyDepthCameraSensor from library /media/data/subt/thirdparty/ws/devel_n/lib/libgazebo_noisy_depth_camera.so
[Msg] Loading world file [/tmp/depth_camera.world]
[Msg] Noisy depth camera loaded
```

```
$ gzclient
# Ctrl+T, select the image topic ~/camera_model/my_link/camera/image
```

![Snímek obrazovky pořízený 2024-11-16 14-03-57](https://github.com/user-attachments/assets/33db8098-e28c-4186-aaa5-ad69a6c4d58f)

**Comment by peci1** [comment]
Oh, I've digged deeper and found out that you were right. I saw the correct result because I was looking at the Gazebo topic. But when used together with a gazebo_ros plugin, the ROS image would be unaffected.

I found a rather hacky way to fix this by manually putting the callback to the first place in the callback list. It uses a fragile technique that depends on https://github.com/gazebosim/gazebo-classic/blob/gazebo11/gazebo/rendering/DepthCameraPrivate.hh not changing. However, this file hasn't changed throughout the whole Gazebo 11 lifetime and Gazebo 11 is almost EOL, so I guess we can bet on this.

With the latest fix, I got the noise working even in rqt_image_view!

**Comment by peci1** [comment]
I've also made a Noetic release of this package: https://github.com/ros/rosdistro/pull/43529 . I hope it will play well being built on the buildfarm against the older Gazebo version ROS uses and then being used with the newest version from OSRF repo. It should!
